// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: proto/pyramid/types/block.proto

package types

import (
	third_party "emulator/proto/third_party"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockType          int32                  `protobuf:"varint,1,opt,name=BlockType,proto3" json:"BlockType,omitempty"`
	HashPointer        []byte                 `protobuf:"bytes,2,opt,name=HashPointer,proto3" json:"HashPointer,omitempty"`
	ChainID            string                 `protobuf:"bytes,3,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	Height             int64                  `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	Time               *third_party.Timestamp `protobuf:"bytes,5,opt,name=Time,proto3" json:"Time,omitempty"`
	BodyRoot           []byte                 `protobuf:"bytes,6,opt,name=BodyRoot,proto3" json:"BodyRoot,omitempty"`
	StateRoot          []byte                 `protobuf:"bytes,8,opt,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	ReceiptRoot        []byte                 `protobuf:"bytes,9,opt,name=ReceiptRoot,proto3" json:"ReceiptRoot,omitempty"`
	RelationRoot       []byte                 `protobuf:"bytes,7,opt,name=RelationRoot,proto3" json:"RelationRoot,omitempty"`
	CrossShardBodyRoot []byte                 `protobuf:"bytes,10,opt,name=CrossShardBodyRoot,proto3" json:"CrossShardBodyRoot,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_block_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetBlockType() int32 {
	if x != nil {
		return x.BlockType
	}
	return 0
}

func (x *Header) GetHashPointer() []byte {
	if x != nil {
		return x.HashPointer
	}
	return nil
}

func (x *Header) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

func (x *Header) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Header) GetTime() *third_party.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Header) GetBodyRoot() []byte {
	if x != nil {
		return x.BodyRoot
	}
	return nil
}

func (x *Header) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *Header) GetReceiptRoot() []byte {
	if x != nil {
		return x.ReceiptRoot
	}
	return nil
}

func (x *Header) GetRelationRoot() []byte {
	if x != nil {
		return x.RelationRoot
	}
	return nil
}

func (x *Header) GetCrossShardBodyRoot() []byte {
	if x != nil {
		return x.CrossShardBodyRoot
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64    `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Round     int32    `protobuf:"varint,2,opt,name=Round,proto3" json:"Round,omitempty"`
	BlockHash []byte   `protobuf:"bytes,3,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	Sigs      [][]byte `protobuf:"bytes,4,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
}

func (x *Commit) Reset() {
	*x = Commit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_block_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_block_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_block_proto_rawDescGZIP(), []int{1}
}

func (x *Commit) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Commit) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Commit) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Commit) GetSigs() [][]byte {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type Relation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelatedCommitStatus [][]byte `protobuf:"bytes,1,rep,name=related_commit_status,json=relatedCommitStatus,proto3" json:"related_commit_status,omitempty"`
	RelatedHash         [][]byte `protobuf:"bytes,2,rep,name=related_hash,json=relatedHash,proto3" json:"related_hash,omitempty"`
	MyCommitStatus      []byte   `protobuf:"bytes,3,opt,name=my_commit_status,json=myCommitStatus,proto3" json:"my_commit_status,omitempty"` //Commit last_commit = 4;
}

func (x *Relation) Reset() {
	*x = Relation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_block_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_block_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_block_proto_rawDescGZIP(), []int{2}
}

func (x *Relation) GetRelatedCommitStatus() [][]byte {
	if x != nil {
		return x.RelatedCommitStatus
	}
	return nil
}

func (x *Relation) GetRelatedHash() [][]byte {
	if x != nil {
		return x.RelatedHash
	}
	return nil
}

func (x *Relation) GetMyCommitStatus() []byte {
	if x != nil {
		return x.MyCommitStatus
	}
	return nil
}

type Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txs [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
}

func (x *Body) Reset() {
	*x = Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_block_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_block_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_block_proto_rawDescGZIP(), []int{3}
}

func (x *Body) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

type CrossShardBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txs             [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	CrossShardDatas [][]byte `protobuf:"bytes,2,rep,name=cross_shard_datas,json=crossShardDatas,proto3" json:"cross_shard_datas,omitempty"`
}

func (x *CrossShardBody) Reset() {
	*x = CrossShardBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_block_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossShardBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossShardBody) ProtoMessage() {}

func (x *CrossShardBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_block_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossShardBody.ProtoReflect.Descriptor instead.
func (*CrossShardBody) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_block_proto_rawDescGZIP(), []int{4}
}

func (x *CrossShardBody) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *CrossShardBody) GetCrossShardDatas() [][]byte {
	if x != nil {
		return x.CrossShardDatas
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header         *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body           *Body           `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	CrossShardBody *CrossShardBody `protobuf:"bytes,3,opt,name=CrossShardBody,proto3" json:"CrossShardBody,omitempty"`
	Relation       *Relation       `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_block_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_block_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_block_proto_rawDescGZIP(), []int{5}
}

func (x *Block) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Block) GetCrossShardBody() *CrossShardBody {
	if x != nil {
		return x.CrossShardBody
	}
	return nil
}

func (x *Block) GetRelation() *Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

var File_proto_pyramid_types_block_proto protoreflect.FileDescriptor

var file_proto_pyramid_types_block_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x70, 0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x1a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xda, 0x02, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x48, 0x61, 0x73, 0x68, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x48, 0x61, 0x73, 0x68, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x2e, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6f, 0x74,
	0x12, 0x2e, 0x0a, 0x12, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x68, 0x61, 0x72, 0x64, 0x42, 0x6f,
	0x64, 0x79, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x43, 0x72,
	0x6f, 0x73, 0x73, 0x53, 0x68, 0x61, 0x72, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x6f, 0x6f, 0x74,
	0x22, 0x68, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x08, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x15, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x13, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x28,
	0x0a, 0x10, 0x6d, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6d, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x18, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x74,
	0x78, 0x73, 0x22, 0x4e, 0x0a, 0x0e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x5f,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x0f, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x68, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x22, 0xdb, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2d, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x79, 0x72, 0x61,
	0x6d, 0x69, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x45, 0x0a, 0x0e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x6f,
	0x73, 0x73, 0x53, 0x68, 0x61, 0x72, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x0e, 0x43, 0x72, 0x6f,
	0x73, 0x73, 0x53, 0x68, 0x61, 0x72, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x33, 0x0a, 0x08, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x1e, 0x5a, 0x1c, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pyramid_types_block_proto_rawDescOnce sync.Once
	file_proto_pyramid_types_block_proto_rawDescData = file_proto_pyramid_types_block_proto_rawDesc
)

func file_proto_pyramid_types_block_proto_rawDescGZIP() []byte {
	file_proto_pyramid_types_block_proto_rawDescOnce.Do(func() {
		file_proto_pyramid_types_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pyramid_types_block_proto_rawDescData)
	})
	return file_proto_pyramid_types_block_proto_rawDescData
}

var file_proto_pyramid_types_block_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_pyramid_types_block_proto_goTypes = []interface{}{
	(*Header)(nil),                // 0: pyramid.types.Header
	(*Commit)(nil),                // 1: pyramid.types.Commit
	(*Relation)(nil),              // 2: pyramid.types.Relation
	(*Body)(nil),                  // 3: pyramid.types.Body
	(*CrossShardBody)(nil),        // 4: pyramid.types.CrossShardBody
	(*Block)(nil),                 // 5: pyramid.types.Block
	(*third_party.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_pyramid_types_block_proto_depIdxs = []int32{
	6, // 0: pyramid.types.Header.Time:type_name -> google.protobuf.Timestamp
	0, // 1: pyramid.types.Block.header:type_name -> pyramid.types.Header
	3, // 2: pyramid.types.Block.body:type_name -> pyramid.types.Body
	4, // 3: pyramid.types.Block.CrossShardBody:type_name -> pyramid.types.CrossShardBody
	2, // 4: pyramid.types.Block.relation:type_name -> pyramid.types.Relation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_pyramid_types_block_proto_init() }
func file_proto_pyramid_types_block_proto_init() {
	if File_proto_pyramid_types_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pyramid_types_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pyramid_types_block_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pyramid_types_block_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Relation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pyramid_types_block_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pyramid_types_block_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossShardBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pyramid_types_block_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pyramid_types_block_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pyramid_types_block_proto_goTypes,
		DependencyIndexes: file_proto_pyramid_types_block_proto_depIdxs,
		MessageInfos:      file_proto_pyramid_types_block_proto_msgTypes,
	}.Build()
	File_proto_pyramid_types_block_proto = out.File
	file_proto_pyramid_types_block_proto_rawDesc = nil
	file_proto_pyramid_types_block_proto_goTypes = nil
	file_proto_pyramid_types_block_proto_depIdxs = nil
}
