// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: proto/pyramid/types/part.proto

package types

import (
	merkle "emulator/proto/crypto/merkle"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Part struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height  int64         `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round   int32         `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Bytes   []byte        `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Proof   *merkle.Proof `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	ChainID string        `protobuf:"bytes,5,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
}

func (x *Part) Reset() {
	*x = Part{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_part_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_part_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_part_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Part) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Part) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Part) GetProof() *merkle.Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Part) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

type PartSetHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   int64  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Root    []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Height  int64  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Round   int32  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	ChainID string `protobuf:"bytes,5,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
}

func (x *PartSetHeader) Reset() {
	*x = PartSetHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pyramid_types_part_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartSetHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartSetHeader) ProtoMessage() {}

func (x *PartSetHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pyramid_types_part_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartSetHeader.ProtoReflect.Descriptor instead.
func (*PartSetHeader) Descriptor() ([]byte, []int) {
	return file_proto_pyramid_types_part_proto_rawDescGZIP(), []int{1}
}

func (x *PartSetHeader) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PartSetHeader) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *PartSetHeader) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PartSetHeader) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PartSetHeader) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

var File_proto_pyramid_types_part_proto protoreflect.FileDescriptor

var file_proto_pyramid_types_part_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x70, 0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a,
	0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x6d, 0x65,
	0x72, 0x6b, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x90, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2a, 0x0a,
	0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x53, 0x65, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x42, 0x1e, 0x5a, 0x1c, 0x65, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x79, 0x72, 0x61, 0x6d, 0x69,
	0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pyramid_types_part_proto_rawDescOnce sync.Once
	file_proto_pyramid_types_part_proto_rawDescData = file_proto_pyramid_types_part_proto_rawDesc
)

func file_proto_pyramid_types_part_proto_rawDescGZIP() []byte {
	file_proto_pyramid_types_part_proto_rawDescOnce.Do(func() {
		file_proto_pyramid_types_part_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pyramid_types_part_proto_rawDescData)
	})
	return file_proto_pyramid_types_part_proto_rawDescData
}

var file_proto_pyramid_types_part_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pyramid_types_part_proto_goTypes = []any{
	(*Part)(nil),          // 0: pyramid.types.Part
	(*PartSetHeader)(nil), // 1: pyramid.types.PartSetHeader
	(*merkle.Proof)(nil),  // 2: crypto.merkle.Proof
}
var file_proto_pyramid_types_part_proto_depIdxs = []int32{
	2, // 0: pyramid.types.Part.proof:type_name -> crypto.merkle.Proof
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pyramid_types_part_proto_init() }
func file_proto_pyramid_types_part_proto_init() {
	if File_proto_pyramid_types_part_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pyramid_types_part_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Part); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pyramid_types_part_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PartSetHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pyramid_types_part_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pyramid_types_part_proto_goTypes,
		DependencyIndexes: file_proto_pyramid_types_part_proto_depIdxs,
		MessageInfos:      file_proto_pyramid_types_part_proto_msgTypes,
	}.Build()
	File_proto_pyramid_types_part_proto = out.File
	file_proto_pyramid_types_part_proto_rawDesc = nil
	file_proto_pyramid_types_part_proto_goTypes = nil
	file_proto_pyramid_types_part_proto_depIdxs = nil
}
